version: "3"
services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis.conf:/redis.conf
    ports:
      - "6696:6696"
    command: redis-server /redis.conf --port 6696
